# Site Settings
title: Start Jekyll
email: christopherstam@yahoo.com
description: >
  A guide to getting started with Jekyll.
baseurl: ""
url: "http://localhost:4000"

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
